### ISSUE TITLE
Can't build the binary

### ISSUE THREAD

**Issue by girishso** [gophergala/dnsp#21]
Thanks for a wonderful project!

When I do a `go get -u github.com/gophergala/dnsp` I can't find the `dnsp` binary in `$GOPATH/bin`.

I am using Mac Yosemite 10.10.1 (14B25), go version 1.4

Any hints will be appreciated.

**Comment by attilaolah** [comment]
Apparently the README is wrong. It should be `go get -u github.com/gophergala/dnsp/...` (note the final `/...`).
