### ISSUE TITLE
Resolve blocked entries to 204 No Content

### ISSUE THREAD

**Issue by girishso** [gophergala/dnsp#22]
Is it possible to resolve the blocked entries to 204 No Content?

Right now the browser keeps waiting for the blocked sites to resolve and effectively stops rendering of the site.

**Comment by attilaolah** [comment]
Unfortunately not. DNS responses are either a proper name resolution, or no name resolution.

---

Well, actually, yes, it would be possible by resolving all blocked sites to localhost (which you can already do with something like `dnsmasq`), and running a server locally that returns a 204 No Content for *all* requests.

The problem with that though is it wouldn't work well with HTTPS, without you having to trust some form of a self-signed certificate, and I don't want that security hole near this project :)
